### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by okdistribute**
@kirakirawes here is the first pass. Do we need to make them all a certain size?

@cafca what would be the best way to format the metadata for each example? (https link, image, and name)

### CODE REVIEW

**Comment by bumbleblue** [comment]
LGTM! I'm wondering how the pictures will figure in?

**Comment by cafca** [comment]
@okdistribute I am still working out how to specify examples. We went over this in today's meeting but ran out of time. I will find a way within the next week.

**Comment by cafca** [comment]
Oh, and the example images will be placed side-by-side with the markdown. C.f. #53

**Comment by okdistribute** [comment]
Awesome. Once we have an idea about how the examples should be formatted, I can then update this PR to move the example images into the proper place with proper metadata

**Comment by okdistribute** [comment]
@bumbleblue said:
> LGTM! I'm wondering how the pictures will figure in?

@kirakirawes has this worked into the design in figma, it's pretty awesome!

**Review by cafca — APPROVED** [review]
Looks good! I noticed that trackers is the only entry that's not capitalized btw.

**Comment by okdistribute** [comment]
Thanks, fixed!

**Pull request merged**
